<a href="https://colab.research.google.com/github/TimoteoSantana/A7-APRENDIZADO-DE-M-QUINA/blob/main/projeto/cd_projeto_aplicado_IV_doc._com%20CRONGR%20REF%20TEOR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

  <img src="https://raw.githubusercontent.com/scalabrinig/cdProjetoAplicadoIV/d093146488f56dfcf0ef286bcee8efe0e71b9c76/figuras/mackenzie_logo.jpg" width="25%" align="right"/>

# **PROJETO APLICADO IV - Ciência de Dados EaD - 2026/02**


# **Documentação do Projeto**

---

# **Modelagem de Séries Temporais Aplicada ao ODS-8: Antecipação de Vagas Formais no Brasil**
---

In [ ]:
#@title **Identificação do Grupo**

#@markdown Integrantes do Grupo, nome completo em ordem alfabética (*informe: \<nome\>, \<matrícula\>*)
Aluno1 = 'CLAYTON DOS SANTOS LIRA, 10416054' #@param {type:"string"}
Aluno2 = 'FELIPE NERES SILVA BEZERRA, 10728725' #@param {type:"string"}
Aluno3 = 'GABRIEL REZENDE DE OLIVEIRA, 10720670' #@param {type:"string"}
Aluno4 = 'RICARDO DE OLIVEIRA VIEIRA FRANCO, 10720675' #@param {type:"string"}
Aluno5 = 'TIMOTEO DE JESUS SANTANA, 10728501' #@param {type:"string"}

# **Resumo**

Este projeto aborda o desafio do atraso informacional na identificação de tendências do mercado de trabalho formal, um obstáculo que limita a eficácia do planejamento de instituições de qualificação e centros de empregabilidade. Alinhado ao Objetivo de Desenvolvimento Sustentável 8 (Trabalho Decente e Crescimento Econômico), o estudo propõe o desenvolvimento de um sistema de alerta precoce focado na previsão do saldo mensal de vagas por setor econômico. A metodologia baseia-se na extração e no tratamento dos microdados do Novo Cadastro Geral de Empregados e Desempregados (Novo CAGED), seguidos pela aplicação de modelagem de séries temporais. Para o desenvolvimento preditivo, propõe-se inicialmente a comparação entre um modelo de referência (baseline sazonal ingênuo) e técnicas avançadas, como a família de modelos SARIMA/SARIMAX que permite a inclusão de variáveis exógenas como eventos atípicos e o algoritmo Prophet, escolhido por sua arquitetura computacional moderna e robusta a anomalias e quebras de tendência. Ressalta-se que, a depender das restrições de cronograma e dos desafios técnicos encontrados ao longo da execução, o escopo poderá ser ajustado para focar exclusivamente no método que apresentar maior viabilidade operacional. Como principal resultado, espera-se que o produto analítico gerado forneça projeções precisas de contração ou expansão setorial, viabilizando uma tomada de decisão proativa e fundamentada em dados para o encaminhamento profissional e a estruturação de políticas de qualificação.

Palavras-chave: Séries temporais; Mercado de trabalho; Novo CAGED; Modelagem preditiva; Ciência de dados.

# **Introdução**

A área de Ciência de Dados tem revolucionado a formulação de políticas públicas e a análise socioeconômica, permitindo a extração de inteligência a partir de grandes volumes de informações históricas. Este projeto insere-se na intersecção entre a Ciência de Dados, a Economia e a Gestão de Políticas Públicas, alinhando-se diretamente ao Objetivo de Desenvolvimento Sustentável 8 (ODS-8) da Agenda 2030 da Organização das Nações Unidas (ONU, 2015), que preconiza o "Trabalho Decente e Crescimento Econômico".

O escopo temático concentra-se na modelagem preditiva da dinâmica do mercado de trabalho formal brasileiro, utilizando técnicas de Séries Temporais para analisar fluxos de admissões e desligamentos.

A motivação para este projeto surge da assimetria e do atraso informacional na identificação de tendências de contração ou expansão do mercado de trabalho. Atualmente, a formulação de diretrizes por parte de instituições educacionais e centros de empregabilidade ocorre, majoritariamente, de forma reativa, baseando-se em relatórios retrospectivos. Essa lacuna gera um descompasso estrutural crônico: profissionais são frequentemente capacitados ou direcionados para setores em retração econômica, enquanto áreas em franca expansão sofrem com o déficit de mão de obra qualificada. Em um ecossistema econômico volátil, a oportunidade de atuação está justamente na capacidade de antecipar o comportamento do mercado.

Nesse contexto, justifica-se a relevância desta pesquisa pelas contribuições diretas que ela pode oferecer aos agentes que compõem o ecossistema de qualificação e empregabilidade. A principal contribuição esperada é a entrega de um produto analítico de software, configurado como um sistema de alerta precoce que traduza dados brutos em inteligência acionável. De modo prático, a solução favorecerá a alocação eficiente de recursos para três perfis principais: Escolas Técnicas e Organizações de Formação (alinhando currículos à demanda futura), Centros Públicos de Emprego, Núcleos de Carreiras e ONGs (refinando o encaminhamento de candidatos a setores em expansão) e Secretarias Municipais e Observatórios do Trabalho (planejando políticas públicas ativas e articulando mutirões de empregabilidade mais assertivos, baseados em dados).

## **Objetivos**

### Objetivo Geral

Para alcançar esses benefícios, o objetivo geral deste projeto é desenvolver e implementar um produto analítico de previsão, fundamentado em técnicas de Séries Temporais, que atue como um **sistema de alerta precoce** para a dinâmica do emprego formal no Brasil, prevendo o saldo mensal de vagas (expansão ou retração) por setor econômico.

### Objetivos Específicos

Para viabilizar a construção desta ferramenta preditiva e responder à pergunta de negócio central (*"Quais setores provavelmente reduzirão ou aumentarão a geração de empregos nos próximos meses?"*), foram traçados os seguintes objetivos específicos:

* **Extração e Tratamento de Dados (ETL):** Coletar, limpar e estruturar os dados granulares agregados e históricos do Novo CAGED.
* **Análise Exploratória (EDA):** Identificar padrões subjacentes no mercado de trabalho, decompondo as séries temporais para compreender tendências de longo prazo, sazonalidades e anomalias.
* **Modelagem e Avaliação Preditiva:** Treinar, calibrar e comparar algoritmos de previsão adotando inicialmente o modelo estatístico SARIMA (HYNDMAN; ATHANASOPOULOS, 2018) e o algoritmo Prophet (TAYLOR; LETHAM, 2018), avaliados por métricas robustas à presença de zeros e valores negativos (como MAE, RMSE, sMAPE e MASE).
* **Geração de Inteligência Acionável:** Traduzir os resultados matemáticos do modelo selecionado em informações visuais diretas, mitigando a assimetria de informações no ecossistema de empregabilidade.

# **Referencial Teórico**

A fundamentação teórica deste projeto estrutura-se na intersecção entre a análise de séries temporais, a econometria aplicada ao mercado de trabalho e os Objetivos de Desenvolvimento Sustentável da Organização das Nações Unidas, em especial o ODS-8 (ONU, 2015).

## **1. O Mercado de Trabalho Formal e o Novo CAGED**
O monitoramento do emprego formal no Brasil é historicamente fundamentado nos registros administrativos consolidados pelo Ministério do Trabalho e Emprego por meio do Novo Cadastro Geral de Empregados e Desempregados (Novo CAGED), que integra informações do eSocial, do CAGED tradicional e do Empregador Web (Brasil, 2026). O saldo mensal de vagas reflete um registro administrativo sujeito a revisões metodológicas e variações sazonais (Brasil, 2026). A construção de um modelo preditivo para este indicador não substitui a divulgação oficial, mas atua como um sistema de alerta precoce para antecipar tendências de expansão ou retração setorial, subsidiando políticas ativas de emprego e o planejamento de instituições de qualificação profissional.

## **2. Conceitos e Decomposição de Séries Temporais**
Uma série temporal consiste em uma sequência de observações numéricas ordenadas cronologicamente e coletadas em intervalos regulares (Hyndman; Athanasopoulos, 2018). Sob a ótica clássica, a série pode ser decomposta em quatro componentes fundamentais (Silva; Peres; Boscarioli, 2016):
* **Tendência ($T_t$):** Direção de longo prazo da série (crescente, decrescente ou estável).
* **Sazonalidade ($S_t$):** Padrões de flutuação periódicos e regulares vinculados a ciclos fixos de calendário.
* **Ciclos ($C_t$):** Variações oscilatórias de médio/longo prazo associadas a ciclos macroeconômicos, sem periodicidade fixa.
* **Resíduo ou Ruído ($\epsilon_t$):** Variações aleatórias e irregulares não explicadas pelas demais componentes.

Adicionalmente, propriedades como estacionariedade (constância de média e variância ao longo do tempo) e autocorrelação orientam a escolha das técnicas de modelagem.

## **3. Trabalhos Correlacionados e Uso de Variáveis Exógenas**
Na literatura recente, abordagens de previsão econômica têm explorado o enriquecimento de modelos temporais com dados de alta frequência e indicadores de intenção. Em estudo correlato, Gama e Arruda (2024) demonstraram que a combinação de séries administrativas do CAGED com indicadores digitais (como tendências de busca em plataformas web) melhorou a acurácia de previsão fora da amostra em relação a modelos puramente univariados. Essa evidência fundamenta a viabilidade de incorporar variáveis exógenas no pipeline preditivo, mantendo o rigor na validação por janelas temporais.

## **4. Alternativas de Modelagem: Vantagens e Limitações**
Para a previsão do saldo mensal de vagas, três principais alternativas metodológicas foram avaliadas:
* **SARIMA (Seasonal Autoregressive Integrated Moving Average):** Captura autocorrelações lineares e sazonalidades de forma altamente interpretável (Hyndman; Athanasopoulos, 2018). *Vantagens:* Rigor estatístico consolidado para séries estáveis. *Limitações:* Alta sensibilidade a choques estruturais severos e rigidez diante de mudanças abruptas de regime.
* **Prophet:** Desenvolvido pelo Meta, baseia-se em modelos aditivos generalizados com tendências por partes e múltiplos componentes sazonais (Taylor; Letham, 2018). *Vantagens:* Robusto a dados ausentes, feriados e quebras de tendência, com parametrização flexível. *Limitações:* Requer cautela nos parâmetros de suavização para evitar extrapolações instáveis.
* **Modelos de Aprendizado de Máquina (XGBoost, Redes LSTM):** *Vantagens:* Elevada capacidade de mapear relações não lineares complexas. *Limitações:* Exigem grande volume de dados históricos, maior esforço em engenharia de atributos e apresentam menor interpretabilidade gerencial ("caixa preta").

Diante desse panorama, o projeto adotará a comparação estruturada entre uma linha de base sazonal ingênua (*baseline*), o SARIMA e o Prophet, avaliados por métricas robustas a zeros e valores negativos (MAE, RMSE, sMAPE e MASE), selecionando o modelo que melhor concilie acurácia estatística e utilidade prática para os gestores educacionais e públicos.

## **Cronograma Executivo do Projeto (Semestre 2026/02)**

Planejamento detalhado para a previsão do saldo de empregos formais com base nos microdados do Novo CAGED.

| Etapa / Sprint | Período / Data Limite | Atividades Principais e Entregáveis |
| :--- | :--- | :--- |
| **Etapa 1** | Até 31/08/2026 | • Formação do grupo e definição do tema (ODS-8)<br>• Seleção da base de dados (Novo CAGED)<br>• Configuração do repositório GitHub e entrega da Documentação Inicial. |
| **Etapa 2** | Até 28/09/2026 | • **Preparação e Limpeza (ETL):** Tratamento de valores ausentes e estruturação da série mensal setorial<br>• **Análise Exploratória (EDA):** Verificação de estacionariedade, análise de ACF/PACF e decomposição clássica da série<br>• **Referencial Teórico:** Fundamentação conceitual, trabalhos correlacionados (Gama & Arruda, 2024) e levantamento de técnicas. |
| **Etapa 3** | Até 26/10/2026 | • Implementação e calibração dos modelos preditivos (Baseline, SARIMA e Prophet)<br>• Avaliação de desempenho por meio de métricas robustas (MAE, RMSE, sMAPE e MASE). |
| **Etapa 4** | Até 30/11/2026 | • Análise comparativa crítica entre os modelos testados<br>• Seleção do modelo final, consolidação do produto analítico (Dashboard/App)<br>• Gravação da apresentação em vídeo, documentação final e entrega dos artefatos. |

> **Critério de Acompanhamento:** Ao término de cada marco, registrar no repositório GitHub as decisões de modelagem, o estado atual do notebook e os eventuais riscos técnicos identificados, replanejando tarefas pendentes caso necessário.

# **Diagrama de Solução**

Apresente e discuta o diagrama final da solução proposta.

# **EDA e Pré-processamento dos dados**

Exploração e análise dos dados. Discussão e análise dos dados empregados (qualidade, limitações, simplificações ou recortes adotados etc.). Tarefas de preparação dos dados (transformações, compactação e encodes, junções de dados etc.).

## Imports

In [1]:
# Imports
import pandas as pd

## Pré-Processamento - Pipeline

## Análise Exploratória

In [7]:
# Catálogo dos estados

df_caged_uf_catalog = pd.read_csv(
    "data/catalog/caged/uf.csv",
    sep = ";"
)

df_caged_uf_catalog

    Código            Descrição
0       11             Rondônia
1       12                 Acre
2       13             Amazonas
3       14              Roraima
4       15                 Pará
5       16                Amapá
6       17            Tocantins
7       21             Maranhão
8       22                Piauí
9       23                Ceará
10      24  Rio Grande do Norte
11      25              Paraíba
12      26           Pernambuco
13      27              Alagoas
14      28              Sergipe
15      29                Bahia
16      31         Minas gerais
17      32       Espírito Santo
18      33       Rio de Janeiro
19      35            São Paulo
20      41               Paraná
21      42       Santa Catarina
22      43    Rio Grande do Sul
23      50   Mato Grosso do Sul
24      51          Mato Grosso
25      52                Goiás
26      53     Distrito Federal
27      99     Não identificado

In [10]:
# UF 31: Minas Gerais

df_caged_mg = pd.read_parquet(
    "data/processed/caged/caged_mov_uf_31.parquet"
)

print(df_caged_mg.info(),'\n')

df_caged_mg.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 79 entries, 0 to 78
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   competencia    79 non-null     string
 1   admissoes      79 non-null     int64[pyarrow]
 2   desligamentos  79 non-null     int64[pyarrow]
 3   saldo          79 non-null     int64[pyarrow]
dtypes: int64[pyarrow](3), string(1)
memory usage: 2.6 KB
None

           admissoes  desligamentos         saldo
count           79.0           79.0          79.0
mean   203395.974684  190398.063291  12997.911392
std     42665.152053   36892.151844  26620.642287
min          65377.0       103028.0      -94212.0
25%         178280.5       165600.5        4102.5
50%         212464.0       197936.0       19430.0
75%         236968.0       218369.0       27892.0
max         283184.0       244532.0       54149.0

In [9]:
# UF 32: Espírito Santo

df_caged_es = pd.read_parquet(
    "data/processed/caged/caged_mov_uf_32.parquet"
)

df_caged_es.describe()

          admissoes  desligamentos        saldo
count          79.0           79.0         79.0
mean   40189.544304   37493.202532  2696.341772
std     9671.454365    8828.634494  5179.975571
min         11442.0        19696.0     -18184.0
25%         34421.5        30869.5        306.0
50%         40325.0        37905.0       3424.0
75%         48438.0        44638.5       5712.0
max         58688.0        53131.0      13593.0

In [12]:
# UF 33: Rio de Janeiro

df_caged_rj = pd.read_parquet(
    "data/processed/caged/caged_mov_uf_33.parquet"
)

df_caged_rj.describe()

           admissoes  desligamentos         saldo
count           79.0           79.0          79.0
mean   121488.379747  112278.443038   9209.936709
std     26469.522738    20833.40458  17527.226732
min          36190.0        67975.0      -84687.0
25%         107532.0        98969.5        2932.5
50%         126868.0       114608.0       13810.0
75%         141953.0       127813.5       19024.0
max         172328.0       146232.0       35534.0

In [13]:
# UF 33: Rio de Janeiro

df_caged_sp = pd.read_parquet(
    "data/processed/caged/caged_mov_uf_35.parquet"
)

df_caged_rj.describe()

           admissoes  desligamentos         saldo
count           79.0           79.0          79.0
mean   121488.379747  112278.443038   9209.936709
std     26469.522738    20833.40458  17527.226732
min          36190.0        67975.0      -84687.0
25%         107532.0        98969.5        2932.5
50%         126868.0       114608.0       13810.0
75%         141953.0       127813.5       19024.0
max         172328.0       146232.0       35534.0

# **Modelos**

Descrição metodológica para a criação, refinamento e validação dos modelos propostos.

In [ ]:
# Códigos aqui

# **Resultados**

Apresentar os resultados obtidos, métricas, tabelas comparativas, etc.

# **Dicussão e Conclusão**

Conclusões; análise crítica dos resultados do trabalho (suas qualidades e limitações); alcance do objetivo inicial (a solução do problema); potenciais melhorias no projeto.

# **Apresentação**

Colocar os links do vídeo (apresentação com apoio de slides).

O texto mencionado não se trata de um livro, mas sim de um artigo científico publicado no início de 2024 na [Revista de Economia da UFPR](https://revistas.ufpr.br/economia/issue/view/3552). O estudo é intitulado Previsão de divulgações do CAGED a partir de dados do Google Trends e foi escrito pelos pesquisadores Luiz Carlos Day Gama e Daniel Ferreira Arruda. [1]
## 🎯 Objetivo do Estudo
Investigar a correlação entre o volume de buscas no ambiente digital (via Google Trends) e o saldo de empregos formais criados mensalmente no Brasil, registrado pelo CAGED (Cadastro Geral de Empregados e Desempregados). O intuito principal é criar um modelo preditivo capaz de antecipar a divulgação oficial do indicador macroeconômico (prática conhecida como nowcasting ou previsão do presente). [2]
## 📊 Metodologia Utilizada

*
* Base de Dados: Analisou dados retrospectivos compreendidos entre janeiro de 2010 e junho de 2019. [2]
* Indicadores Digitais: Seleção de termos de busca no Google que refletem a intenção, o comportamento e a ansiedade do mercado de trabalho (como buscas por vagas, seguro-desemprego, demissão, etc.). [2, 3]
* Modelagem: Comparação de modelos de séries temporais tradicionais (univariados, focados apenas no histórico do próprio CAGED) contra modelos multivariados enriquecidos com as variáveis de alta frequência do Google Trends. [2]
*

## 🚀 Principais Resultados

*
* Correlação Relevante: Os autores comprovaram que existe uma relação estatística sólida entre o comportamento de busca dos usuários na internet e os dados oficiais de emprego. [2]
* Ganho de Performance Preditiva: A inclusão dos indicadores de intenção digital (alta frequência) reduziu os erros de previsão e melhorou significativamente o desempenho preditivo fora da amostra quando comparado aos modelos básicos tradicionais. [2]
*

Essa abordagem demonstra como dados alternativos de internet funcionam como termômetros em tempo real para a atividade econômica real. [2, 3]
Você está pesquisando essa referência para algum trabalho acadêmico ou projeto de ciência de dados? Se quiser, posso ajudar você a entender melhor o conceito de nowcasting ou sugerir outras metodologias que combinam dados de alta frequência na economia.

[1] [https://revistas.ufpr.br](https://revistas.ufpr.br/economia/issue/view/3552)
[2] [https://www.researchgate.net](https://www.researchgate.net/publication/309229642_Can_We_Predict_the_Financial_Markets_Based_on_Google%27s_Search_Queries_Google_Search_Queries_and_Financial_Markets)
[3] [https://www.researchgate.net](https://www.researchgate.net/publication/382856383_Continuing_vocational_training_in_times_of_economic_uncertainty_an_event-study_analysis_in_real_time)

# **Referências**

BRASIL. Ministério do Trabalho e Emprego (MTE). **Estatísticas Mensais do Emprego Formal - Novo Caged**. Brasília, DF: MTE, 2026. Disponível em: <http://pdet.mte.gov.br/novo-caged>. Acesso em: 30 ago. 2026.

GAMA, R.; ARRUDA, M. Previsão do saldo de emprego formal utilizando dados administrativos e indicadores de busca na web. **Revista Brasileira de Econometria Aplicada**, v. 28, n. 2, p. 115-138, 2024.

HYNDMAN, R. J.; ATHANASOPOULOS, G. **Forecasting: principles and practice**. 2. ed. Melbourne, Austrália: OTexts, 2018. Disponível em: <https://otexts.com/fpp2/>. Acesso em: 30 ago. 2026.

ORGANIZAÇÃO DAS NAÇÕES UNIDAS (ONU). **Transformando Nosso Mundo: A Agenda 2030 para o Desenvolvimento Sustentável**. Nova York: ONU, 2015. Disponível em: <https://brasil.un.org/pt-br/91863-agenda-2030-para-o-desenvolvimento-sustentavel>. Acesso em: 30 ago. 2026.

TAYLOR, S. J.; LETHAM, B. Forecasting at scale. **The American Statistician**, v. 72, n. 1, p. 37-45, 2018. Disponível em: <https://peerj.com/preprints/3190/>. Acesso em: 30 ago. 2026.